version: '3'

services:
  db:
    image: ankane/pgvector
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=Casket-Condone8-Name
      - POSTGRES_USER=postgres
      - POSTGRES_DB=database

volumes:
  db: